POST http://localhost:3000/playlist/create HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "youtubeID": "BQAt0a8Omk1vpKvGfVJaCsMUJL-7nq1re7xDgqiG-ju4AMiHfy3V8ipuGkntWG_2FJPZfgAPcRcDJXQlSxz0GC1fw9PScDASrsek8_EWZFsMqVpkdrL4Mg8d3WdkOxjbx792QbaYIAd-FHMOQCi-IKZPJIr-uYxUKL3u46E282fFRRpFMYlab7rGzpz0vhJdEcifIBroOJgqAm_N0jk",
    "name": "Essential '90s Hip Hop",
    "spotifyToken": ""
}
###